# Generated by Django 3.2.5 on 2021-07-06 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=30)),
                ('dt_criacao', models.CharField(default='', max_length=10)),
                ('descricao', models.CharField(default='', max_length=150)),
                ('modulo', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=30)),
                ('cpf', models.CharField(default='', max_length=11)),
                ('telefone', models.CharField(default='', max_length=11)),
                ('nota', models.CharField(default='', max_length=3)),
                ('falta', models.CharField(default='', max_length=3)),
                ('status', models.CharField(default='', max_length=1)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTeologia.turma', verbose_name='the related poll')),
            ],
        ),
    ]
