# Generated by Django 3.2.5 on 2021-07-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTeologia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='modulo',
            field=models.CharField(default='', max_length=3),
        ),
    ]
