# Generated by Django 3.2.5 on 2021-07-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTeologia', '0003_alter_turma_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='nota',
            field=models.CharField(default='', max_length=4),
        ),
    ]
